### ISSUE TITLE
Return is called more than once for nested function calls

### ISSUE THREAD

**Issue by skess42** [vanilla-technologies/mcfunction-debugger#47]
This causes a "Selected entity marker was killed!" error and a depth of -1.

Iterate is called multiple times too, but without a visible effect as no selected_entity_marker AECs are left.

**Comment by Adrodoc** [comment]
We should change how we handle the control flow to solve this:
Instead of `iterate` and `iteration_step` calling each other recusively we should make a new function that either starts the next iteration round or returns to the caller. This new function should be called by the last `-line_numbers-` function (or maybe `-line_numbers-_with_context`).

**Comment by Adrodoc** [comment]
It turns out this is not caused by what I thought initially. I thought this was caused by the fact that for a nested function call the intermediate `return` is executed both by the intermediate function call itself and by the continue (called from the nested functions `return`).
It turns out the intermediate function call doesn't return in that case, because the `function_call` AEC is killed by the first `return` (in `continue`) and this line doesn't do anything: https://github.com/vanilla-technologies/mcfunction-debugger/blob/2062f1708cdd75507b97019ed93e7df353914b70/src/datapack_template/data/template/functions/call_function.mcfunction#L30
Instead this bug occurs because in `return` we first dispatch to the correct `continue` and then kill the `function_call` AEC:
https://github.com/vanilla-technologies/mcfunction-debugger/blob/2062f1708cdd75507b97019ed93e7df353914b70/src/datapack_template/data/-ns-/functions/-orig_ns-/-orig/fn-/return.mcfunction#L22-L24
That means there can be multiple `function_call` AECs alive at the same depth which causes a double return.
Killing the AEC before dispatching solves the issue, but then we operate on a dead AEC, which might not work in future Minecraft versions. To avoid this, we could mark the AEC as "inactive" or so and only consider active ones for returning.

We should also check if all other AECs are killed correctly to avoid similar bugs.

**Comment by Adrodoc** [comment]
the kill in `-line_numbers-_with_context` is only required in the last one.
